CREATE TABLE timezones (
USERID varchar(12) PRIMARY KEY,
TIMECONVERT time(fsp) NOT NULL,
TZFROM varchar(4) NOT NULL,
TZTO varchar(4) NOT NULL,XS
);

INSERT INTO timezones VALUES ('USERID', 'TIMECONVERT', 'TZFROM', 'TZTO');
